name: Atualizar Cards do GitHub

on:
  schedule:
    - cron: "0 3 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Gerar card de estat√≠sticas
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&title_color=6f32f3&bg_color=010617&icon_color=6f32f380&text_color=ffffffd9&include_all_commits=true&count_private=true&border_color=6f32f380&border_radius=10
          path: profile/stats.svg
          token: ${{ secrets.PAT_TOKEN }}

      - name: Gerar card de linguagens
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6&title_color=6f32f3&bg_color=010617&text_color=ffffffd9&border_color=6f32f380&border_radius=10
          path: profile/languages.svg
          token: ${{ secrets.PAT_TOKEN }}

      - name: Salvar cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git add profile/*.svg
          git commit -m "Atualizar cards do GitHub" || exit 0
          git push
